### ISSUE TITLE
Moar Supportz pls

### ISSUE THREAD

**Issue by aceofspades2** [starwarswii/Karel-Z#1]
hello, it is me, your humble amazing app designer. I am use your wonderful Karel-Z program in my app that I am design. but however I unfortunately need a little more support for some small little libraries added pls. the small little libraries are (there's just a few): python, C, C#, C++, brainf*ck, FORTRAN, machine code, perl, ruby, Racket, SKI combinator calculus, trinary, lua, SQL, javascript, PHP, html, xml, .NET, assembly, bash, batch, BASIC, visual C, visual c++, visual c#, A#, c--, Cython, Curl, E#, F#, haskell, J#, Jython, Karel, Karel++, M#, swift, X#, and the few others located at here: [http://tinyurl.com/co2r9la](url). Also, I need it to be has accesses to the stock market datas, team fortress 2 economy datas, weather datas in every major city in the Canada, and every minor city and town in the Earth, full multiplayer supports, and the ability to perform multivariable calculus that I tell it to via telepathic. Also, I need it to be fully artificially intelligent and capable of extreme machine learning which on a scale of rock to (R2D2)^(Hal 9000), it must be superhuman of intelligence. I rlly need this little bit of extra added support pls so if you could do that for me pls i need it by no later then yesterday so thx pls get back to me is super important. ps. pls include full 3d hologram support and it has to run on my apple II at over 9000 fps and have support for the oculus rift and the htc vive at the same time pls thx

**Comment by starwarswii** [comment]
thx
